 #WebApi Build
name: 'Dev/Test Env'
on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Select env:- dev/test/qa/prod'
        required: true
        options:
        - dev
        - test

jobs:
  Build-and-Publish:
    runs-on: [INBL01LAP05520]
    env:
      DOTNET_VERSION: '3.1.x'
      SOLUTIONPATH: ''
      NUGET_VERSION: '5.x'
      deploymentscript: 'deploymetscripts'
    steps:

 #Checkout ES-IaC-test repository

    - name: 'Checkout GitHub Code'
      uses: actions/checkout@v2
      
      
    #Setup dotnet

    - name: Setup DotNet ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: ${{ env.DOTNET_VERSION }}
 
 #Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    #Setup Nuget
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
       nuget-version: ${{env.NUGET_VERSION}}

    - name: Restore dependencies
      run: nuget restore ${{env.SOLUTIONPATH}}

  
    - name: Build Solution
      run: |
          msbuild ${{env.SOLUTIONPATH}} /p:OutputPath=./output
       
    - name: Get Test-Env webconf file 
      if: ${{ github.event.inputs.choice == 'test' }}
      run: |
          ${{ env.deploymentscript }}/testwebconfig.ps1 
          
          
  Deploy-DevEnv:
    runs-on: [self-hosted, Dev]
    if: ${{ github.event.inputs.choice == 'dev' }}
    needs: Build-and-Publish
    environment:
      name: Dev
    
    steps:
    - name: Deploy artifacts to dev Env
      run: |
          dir ${{ github.workspace }}
        
  Deploy-TestEnv:
    runs-on: [self-hosted, Dev]
    if: ${{ github.event.inputs.choice == 'test' }}
    needs: Build-and-Publish
    environment:
      name: test    
    steps:
    - name: Deploy artifacts to Test Env
      run: |
        dir ${{ github.workspace }}
